name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > demo-ec2.pem
          chmod 600 demo-ec2.pem
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -i "demo-ec2.pem" ubuntu@ec2-34-219-63-67.us-west-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
